# project:
#   type: website
#   output-dir: docs

# website:
#   title: "Vega-Altair Blog"
#   navbar:
#     right:
#       - href: index.qmd
#         text: Home
#       - href: blog.qmd
#         text: Blog


# format:
#   html:
#     theme:
#       light: [litera, styles.scss]
#     highlight-style: a11y-dark
#     mainfont: "Roboto"
#     code-copy: true
#     code-overflow: wrap


# execute:
#   freeze: auto

project:
  type: website
  output-dir: docs

website:
  title: "Vega-Altair Blog"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
  page-footer: "footer.qmd"

format:
  html:
    theme:
      light: [litera, styles.scss]  # Using SCSS for custom styling
    highlight-style: a11y-dark
    mainfont: "Poppins"
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto